--Copyright (C) 2017-2024 D4KiR (https://www.gnu.org/licenses/gpl.txt)
include("db/db_database.lua")
include("gm/sv_playerisready.lua")
include("gm/sv_gamemode.lua")
include("gm/sv_net.lua")
include("gm/sv_map.lua")
include("gm/sv_think.lua")
include("gm/sv_chat.lua")
include("gm/sv_teleport.lua")
include("gm/sv_startup.lua")
