--Copyright (C) 2017-2024 D4KiR (https://www.gnu.org/licenses/gpl.txt)
YRP:msg("gm", "Loading sh_includes.lua")
add_luas("db/lang/db_lang.lua")
add_luas("gm/sh_gamemode.lua")
add_luas("gm/sh_player.lua")
add_luas("gm/sh_entity.lua")
add_luas("gm/sh_team.lua")
YRP:msg("gm", "Loaded sh_includes.lua")
