--Copyright (C) 2017 Arno Zura ( https://www.gnu.org/licenses/gpl.txt )

printGM( "note", "Loading cl_includes.lua" )

include( "db/db_database.lua" )

include( "gm/cl_startup.lua" )
include( "gm/cl_hud.lua" )
include( "gm/cl_chat.lua" )
include( "gm/cl_think.lua" )
include( "gm/hud/cl_hud_crosshair.lua" )
include( "gm/hud/cl_hud_map.lua" )
include( "gm/hud/cl_hud_player.lua" )
include( "gm/hud/cl_hud_view.lua" )
include( "gm/menus/cl_help.lua" )
include( "gm/menus/cl_buy.lua" )
include( "gm/menus/cl_character.lua" )
include( "gm/menus/cl_door_options.lua" )
include( "gm/menus/cl_interact.lua" )
include( "gm/menus/cl_inventory.lua" )
include( "gm/menus/cl_rolesmenu.lua" )
include( "gm/menus/cl_scoreboard.lua" )
include( "gm/menus/cl_vehicle_options.lua" )
include( "gm/menus/settings/cl_settings.lua" )
include( "gm/menus/settings/cl_settings_client_charakter.lua" )
include( "gm/menus/settings/cl_settings_client_hud.lua" )
include( "gm/menus/settings/cl_settings_client_keybinds.lua" )
include( "gm/menus/settings/cl_settings_server_general.lua" )
include( "gm/menus/settings/cl_settings_server_realistic.lua" )
include( "gm/menus/settings/cl_settings_server_give.lua" )
include( "gm/menus/settings/cl_settings_server_map.lua" )
include( "gm/menus/settings/cl_settings_server_money.lua" )
include( "gm/menus/settings/cl_settings_server_restriction.lua" )
include( "gm/menus/settings/cl_settings_server_roles.lua" )
include( "gm/menus/settings/cl_settings_server_whitelist.lua" )
include( "gm/menus/settings/cl_settings_yourrp_add_langu.lua" )
include( "gm/menus/settings/cl_settings_yourrp_contact.lua" )
include( "gm/menus/settings/cl_settings_yourrp_workshop.lua" )
include( "gm/menus/cl_smartphone.lua" )

printGM( "note", "Loaded cl_includes.lua" )
