--Copyright (C) 2017-2024 D4KiR (https://www.gnu.org/licenses/gpl.txt)
include("db_fonts.lua")
include("db_keybinds.lua")
include("db_tutorials.lua")
include("db_apps.lua")
include("db_smartphone.lua")